"""001_initial_schema

Revision ID: 42fa92c6dc7c
Revises: 
Create Date: 2026-03-12 19:06:07.449756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42fa92c6dc7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_themes',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_article_themes_active', 'article_themes', ['is_active'], unique=False)
    op.create_table('cities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_cities_active_sort', 'cities', ['is_active', 'sort_order'], unique=False)
    op.create_table('content_blocks',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), server_default='ru', nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('link_label', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=10), server_default='both', nullable=False),
    sa.Column('block_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('text', 'image', 'video', 'gallery', 'link')", name='chk_cb_block_type'),
    sa.CheckConstraint("device_type IN ('mobile', 'desktop', 'both')", name='chk_cb_device_type'),
    sa.CheckConstraint("entity_type IN ('article', 'event', 'doctor_profile', 'organization_document')", name='chk_cb_entity_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_blocks_entity', 'content_blocks', ['entity_type', 'entity_id', 'locale'], unique=False)
    op.create_index('idx_content_blocks_entity_sorted', 'content_blocks', ['entity_type', 'entity_id', 'locale', 'sort_order'], unique=False)
    op.create_table('notification_templates',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('email', 'telegram', name='notification_channel'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pages_seo',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(length=500), nullable=True),
    sa.Column('og_url', sa.String(length=500), nullable=True),
    sa.Column('og_type', sa.String(length=50), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), server_default='summary_large_image', nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('custom_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), server_default='12', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_months > 0', name='chk_plans_duration'),
    sa.CheckConstraint('price > 0', name='chk_plans_price'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_plans_active', 'plans', ['is_active'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('admin', 'manager', 'accountant', 'doctor', 'user', name='user_role'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specializations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_specializations_active_sort', 'specializations', ['is_active', 'sort_order'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('articles',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='article_status'), server_default='draft', nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_articles_author', 'articles', ['author_id'], unique=False)
    op.create_index('idx_articles_status_published', 'articles', ['status', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_is_deleted'), 'articles', ['is_deleted'], unique=False)
    op.create_table('audit_log',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('passport_data', sa.Text(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('specialization_id', sa.UUID(), nullable=True, comment='Deprecated — use doctor_specializations M:N'),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('academic_degree', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('public_email', sa.String(length=255), nullable=True),
    sa.Column('public_phone', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', 'active', 'deactivated', name='doctor_status'), server_default='pending_review', nullable=False),
    sa.Column('has_medical_diploma', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('registration_address', sa.Text(), nullable=True),
    sa.Column('diploma_photo_url', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('colleague_contacts', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_doctor_profiles_active', 'doctor_profiles', ['last_name', 'first_name'], unique=False, postgresql_where="status = 'active'")
    op.create_index('idx_doctor_profiles_city', 'doctor_profiles', ['city_id'], unique=False)
    op.create_index('idx_doctor_profiles_created', 'doctor_profiles', ['created_at'], unique=False)
    op.create_index('idx_doctor_profiles_name', 'doctor_profiles', ['last_name', 'first_name'], unique=False)
    op.create_index('idx_doctor_profiles_specialization', 'doctor_profiles', ['specialization_id'], unique=False)
    op.create_index('idx_doctor_profiles_status', 'doctor_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_is_deleted'), 'doctor_profiles', ['is_deleted'], unique=False)
    op.create_index('uix_doctor_profiles_slug', 'doctor_profiles', ['slug'], unique=True, postgresql_where='slug IS NOT NULL')
    op.create_table('events',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'finished', 'cancelled', name='event_status'), server_default='upcoming', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_events_created_by', 'events', ['created_by'], unique=False)
    op.create_index('idx_events_date', 'events', ['event_date'], unique=False)
    op.create_index('idx_events_status_date', 'events', ['status', 'event_date'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_table('moderation_history',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mod_history_admin', 'moderation_history', ['admin_id'], unique=False)
    op.create_index('idx_mod_history_created', 'moderation_history', ['created_at'], unique=False)
    op.create_index('idx_mod_history_entity', 'moderation_history', ['entity_type', 'entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('email', 'telegram', name='notification_channel'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status'), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notif_status_created', 'notifications', ['status', 'created_at'], unique=False)
    op.create_index('idx_notif_template', 'notifications', ['template_code'], unique=False)
    op.create_index('idx_notif_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table('organization_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_org_docs_active_sort', 'organization_documents', ['is_active', 'sort_order'], unique=False)
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'pending_payment', 'cancelled', name='subscription_status'), server_default='pending_payment', nullable=False),
    sa.Column('is_first_year', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at', name='chk_subs_dates'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subs_ends_at', 'subscriptions', ['ends_at'], unique=False)
    op.create_index('idx_subs_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subs_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('telegram_bindings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('auth_code', sa.String(length=10), nullable=True),
    sa.Column('auth_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_in_channel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('uix_tg_auth_code', 'telegram_bindings', ['auth_code'], unique=True, postgresql_where='auth_code IS NOT NULL')
    op.create_index('uix_tg_user_id', 'telegram_bindings', ['tg_user_id'], unique=True, postgresql_where='tg_user_id IS NOT NULL')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('voting_sessions',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', 'cancelled', name='voting_session_status'), server_default='draft', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='chk_voting_dates'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voting_dates', 'voting_sessions', ['starts_at', 'ends_at'], unique=False)
    op.create_index('idx_voting_status', 'voting_sessions', ['status'], unique=False)
    op.create_table('article_theme_assignments',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['article_themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'theme_id', name='uix_ata_article_theme')
    )
    op.create_index('idx_ata_article', 'article_theme_assignments', ['article_id'], unique=False)
    op.create_index('idx_ata_theme', 'article_theme_assignments', ['theme_id'], unique=False)
    op.create_table('certificates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('certificate_type', sa.Enum('member', 'event', name='certificate_type'), server_default='member', nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('year >= 2020 AND year <= 2100', name='chk_certs_year'),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_index('idx_certs_type', 'certificates', ['certificate_type'], unique=False)
    op.create_index('idx_certs_user', 'certificates', ['user_id'], unique=False)
    op.create_index('uix_certs_event', 'certificates', ['doctor_profile_id', 'event_id'], unique=True, postgresql_where="certificate_type = 'event' AND event_id IS NOT NULL")
    op.create_index('uix_certs_member_year', 'certificates', ['doctor_profile_id', 'year'], unique=True, postgresql_where="certificate_type = 'member'")
    op.create_table('doctor_documents',
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('medical_diploma', 'retraining_cert', 'oncology_cert', 'additional_cert', name='document_type'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doctor_docs_profile', 'doctor_documents', ['doctor_profile_id'], unique=False)
    op.create_index('idx_doctor_docs_type', 'doctor_documents', ['document_type'], unique=False)
    op.create_table('doctor_profile_changes',
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_fields', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='change_status'), server_default='pending', nullable=False),
    sa.Column('moderation_comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_changes_fields', 'doctor_profile_changes', ['changed_fields'], unique=False, postgresql_using='gin')
    op.create_index('idx_profile_changes_profile', 'doctor_profile_changes', ['doctor_profile_id', 'status'], unique=False)
    op.create_index('uix_profile_changes_pending', 'doctor_profile_changes', ['doctor_profile_id'], unique=True, postgresql_where="status = 'pending'")
    op.create_table('doctor_specializations',
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('doctor_profile_id', 'specialization_id')
    )
    op.create_index('idx_doctor_specializations_spec', 'doctor_specializations', ['specialization_id'], unique=False)
    op.create_table('event_galleries',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('access_level', sa.Enum('public', 'members_only', 'participants_only', name='access_level'), server_default='public', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_galleries_event_access', 'event_galleries', ['event_id', 'access_level'], unique=False)
    op.create_table('event_recordings',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('video_source', sa.Enum('uploaded', 'external', name='video_source'), nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('video_file_key', sa.String(length=500), nullable=True),
    sa.Column('video_file_size', sa.BigInteger(), nullable=True),
    sa.Column('video_mime_type', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('access_level', sa.Enum('public', 'members_only', 'participants_only', name='access_level'), server_default='participants_only', nullable=False),
    sa.Column('status', sa.Enum('hidden', 'published', name='recording_status'), server_default='hidden', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(video_source = 'external' AND video_url IS NOT NULL) OR (video_source = 'uploaded' AND video_file_key IS NOT NULL)", name='chk_recording_source'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recordings_event_status', 'event_recordings', ['event_id', 'status'], unique=False)
    op.create_table('event_tariffs',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('member_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('seats_limit', sa.Integer(), nullable=True),
    sa.Column('seats_taken', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('member_price >= 0', name='chk_tariffs_member_price'),
    sa.CheckConstraint('price >= 0', name='chk_tariffs_price'),
    sa.CheckConstraint('seats_limit IS NULL OR seats_limit > 0', name='chk_tariffs_seats_limit'),
    sa.CheckConstraint('seats_taken >= 0', name='chk_tariffs_seats_taken'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tariffs_event_active', 'event_tariffs', ['event_id', 'is_active'], unique=False)
    op.create_table('voting_candidates',
    sa.Column('voting_session_id', sa.UUID(), nullable=False),
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voting_session_id', 'doctor_profile_id', name='uix_candidates_session_profile')
    )
    op.create_index('idx_candidates_profile', 'voting_candidates', ['doctor_profile_id'], unique=False)
    op.create_table('event_gallery_photos',
    sa.Column('gallery_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['event_galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gallery_photos_sort', 'event_gallery_photos', ['gallery_id', 'sort_order'], unique=False)
    op.create_table('event_registrations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_tariff_id', sa.UUID(), nullable=False),
    sa.Column('applied_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_member_price', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='event_registration_status'), server_default='pending', nullable=False),
    sa.Column('guest_full_name', sa.String(length=300), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_workplace', sa.String(length=255), nullable=True),
    sa.Column('guest_specialization', sa.String(length=255), nullable=True),
    sa.Column('fiscal_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('applied_price >= 0', name='chk_reg_price'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_tariff_id'], ['event_tariffs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'event_tariff_id', name='uix_event_reg_user_event_tariff')
    )
    op.create_index('idx_event_reg_event', 'event_registrations', ['event_id'], unique=False)
    op.create_index('idx_event_reg_status', 'event_registrations', ['status'], unique=False)
    op.create_index('idx_event_reg_tariff', 'event_registrations', ['event_tariff_id'], unique=False)
    op.create_table('votes',
    sa.Column('voting_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['voting_candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voting_session_id', 'user_id', name='uix_votes_session_user')
    )
    op.create_index('idx_votes_candidate', 'votes', ['candidate_id'], unique=False)
    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_type', sa.Enum('entry_fee', 'subscription', 'event', name='product_type'), nullable=False),
    sa.Column('payment_provider', sa.Enum('yookassa', 'psb', 'manual', name='payment_provider'), server_default='yookassa', nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'partially_refunded', 'refunded', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('event_registration_id', sa.UUID(), nullable=True),
    sa.Column('external_payment_id', sa.String(length=255), nullable=True),
    sa.Column('external_payment_url', sa.String(length=1000), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_payments_amount_positive'),
    sa.ForeignKeyConstraint(['event_registration_id'], ['event_registrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('idx_payments_event_reg', 'payments', ['event_registration_id'], unique=False)
    op.create_index('idx_payments_product_type', 'payments', ['product_type'], unique=False)
    op.create_index('idx_payments_provider', 'payments', ['payment_provider'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_subscription', 'payments', ['subscription_id'], unique=False)
    op.create_index('idx_payments_user_created', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_index('uix_payments_external_id', 'payments', ['external_payment_id'], unique=True, postgresql_where='external_payment_id IS NOT NULL')
    op.create_index('uix_payments_idempotency', 'payments', ['idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_table('receipts',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('receipt_type', sa.Enum('payment', 'refund', name='receipt_type'), server_default='payment', nullable=False),
    sa.Column('provider_receipt_id', sa.String(length=255), nullable=True),
    sa.Column('fiscal_number', sa.String(length=100), nullable=True),
    sa.Column('fiscal_document', sa.String(length=100), nullable=True),
    sa.Column('fiscal_sign', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=1000), nullable=True),
    sa.Column('receipt_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='receipt_status'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_receipts_amount_positive'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'receipt_type', name='uix_receipts_payment_type')
    )
    op.create_index('idx_receipts_payment', 'receipts', ['payment_id'], unique=False)
    op.create_index('idx_receipts_status', 'receipts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receipts_status', table_name='receipts')
    op.drop_index('idx_receipts_payment', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('uix_payments_idempotency', table_name='payments', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index('uix_payments_external_id', table_name='payments', postgresql_where='external_payment_id IS NOT NULL')
    op.drop_index('idx_payments_user_created', table_name='payments')
    op.drop_index('idx_payments_subscription', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_provider', table_name='payments')
    op.drop_index('idx_payments_product_type', table_name='payments')
    op.drop_index('idx_payments_event_reg', table_name='payments')
    op.drop_index('idx_payments_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_votes_candidate', table_name='votes')
    op.drop_table('votes')
    op.drop_index('idx_event_reg_tariff', table_name='event_registrations')
    op.drop_index('idx_event_reg_status', table_name='event_registrations')
    op.drop_index('idx_event_reg_event', table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index('idx_gallery_photos_sort', table_name='event_gallery_photos')
    op.drop_table('event_gallery_photos')
    op.drop_index('idx_candidates_profile', table_name='voting_candidates')
    op.drop_table('voting_candidates')
    op.drop_index('idx_tariffs_event_active', table_name='event_tariffs')
    op.drop_table('event_tariffs')
    op.drop_index('idx_recordings_event_status', table_name='event_recordings')
    op.drop_table('event_recordings')
    op.drop_index('idx_galleries_event_access', table_name='event_galleries')
    op.drop_table('event_galleries')
    op.drop_index('idx_doctor_specializations_spec', table_name='doctor_specializations')
    op.drop_table('doctor_specializations')
    op.drop_index('uix_profile_changes_pending', table_name='doctor_profile_changes', postgresql_where="status = 'pending'")
    op.drop_index('idx_profile_changes_profile', table_name='doctor_profile_changes')
    op.drop_index('idx_profile_changes_fields', table_name='doctor_profile_changes', postgresql_using='gin')
    op.drop_table('doctor_profile_changes')
    op.drop_index('idx_doctor_docs_type', table_name='doctor_documents')
    op.drop_index('idx_doctor_docs_profile', table_name='doctor_documents')
    op.drop_table('doctor_documents')
    op.drop_index('uix_certs_member_year', table_name='certificates', postgresql_where="certificate_type = 'member'")
    op.drop_index('uix_certs_event', table_name='certificates', postgresql_where="certificate_type = 'event' AND event_id IS NOT NULL")
    op.drop_index('idx_certs_user', table_name='certificates')
    op.drop_index('idx_certs_type', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('idx_ata_theme', table_name='article_theme_assignments')
    op.drop_index('idx_ata_article', table_name='article_theme_assignments')
    op.drop_table('article_theme_assignments')
    op.drop_index('idx_voting_status', table_name='voting_sessions')
    op.drop_index('idx_voting_dates', table_name='voting_sessions')
    op.drop_table('voting_sessions')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('uix_tg_user_id', table_name='telegram_bindings', postgresql_where='tg_user_id IS NOT NULL')
    op.drop_index('uix_tg_auth_code', table_name='telegram_bindings', postgresql_where='auth_code IS NOT NULL')
    op.drop_table('telegram_bindings')
    op.drop_index('idx_subs_user_status', table_name='subscriptions')
    op.drop_index('idx_subs_status', table_name='subscriptions')
    op.drop_index('idx_subs_ends_at', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('site_settings')
    op.drop_index('idx_org_docs_active_sort', table_name='organization_documents')
    op.drop_table('organization_documents')
    op.drop_index('idx_notif_user_status', table_name='notifications')
    op.drop_index('idx_notif_template', table_name='notifications')
    op.drop_index('idx_notif_status_created', table_name='notifications')
    op.drop_index('idx_notif_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_mod_history_entity', table_name='moderation_history')
    op.drop_index('idx_mod_history_created', table_name='moderation_history')
    op.drop_index('idx_mod_history_admin', table_name='moderation_history')
    op.drop_table('moderation_history')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index('idx_events_status_date', table_name='events')
    op.drop_index('idx_events_date', table_name='events')
    op.drop_index('idx_events_created_by', table_name='events')
    op.drop_table('events')
    op.drop_index('uix_doctor_profiles_slug', table_name='doctor_profiles', postgresql_where='slug IS NOT NULL')
    op.drop_index(op.f('ix_doctor_profiles_is_deleted'), table_name='doctor_profiles')
    op.drop_index('idx_doctor_profiles_status', table_name='doctor_profiles')
    op.drop_index('idx_doctor_profiles_specialization', table_name='doctor_profiles')
    op.drop_index('idx_doctor_profiles_name', table_name='doctor_profiles')
    op.drop_index('idx_doctor_profiles_created', table_name='doctor_profiles')
    op.drop_index('idx_doctor_profiles_city', table_name='doctor_profiles')
    op.drop_index('idx_doctor_profiles_active', table_name='doctor_profiles', postgresql_where="status = 'active'")
    op.drop_table('doctor_profiles')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_articles_is_deleted'), table_name='articles')
    op.drop_index('idx_articles_status_published', table_name='articles')
    op.drop_index('idx_articles_author', table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_specializations_active_sort', table_name='specializations')
    op.drop_table('specializations')
    op.drop_table('roles')
    op.drop_index('idx_plans_active', table_name='plans')
    op.drop_table('plans')
    op.drop_table('pages_seo')
    op.drop_table('notification_templates')
    op.drop_index('idx_content_blocks_entity_sorted', table_name='content_blocks')
    op.drop_index('idx_content_blocks_entity', table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index('idx_cities_active_sort', table_name='cities')
    op.drop_table('cities')
    op.drop_index('idx_article_themes_active', table_name='article_themes')
    op.drop_table('article_themes')

    for enum_name in (
        "receipt_status",
        "receipt_type",
        "payment_status",
        "payment_provider",
        "product_type",
        "event_registration_status",
        "recording_status",
        "video_source",
        "access_level",
        "change_status",
        "document_type",
        "certificate_type",
        "voting_session_status",
        "subscription_status",
        "notification_status",
        "notification_channel",
        "event_status",
        "doctor_status",
        "article_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
